traits_web/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^', include('traits_web_prototype.urls', namespace='traits_web_prototype')),
    url(r'^admin/', include(admin.site.urls)),
)

traits_web_prototype/urls.py
from django.conf.urls import patterns, url
from traits_web_prototype import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^test/$', views.test, name='test'),
    url(r'^how_it_works/$', views.how_it_works, name='how_it_works'),
    url(r'^materials/$', views.materials, name='materials'),
    url(r'^contacts/$', views.contacts, name='contacts'),
    url(r'^login/$', views.login, name='login'),
    url(r'^signup/$', views.signup, name='signup'),


    url(r'^prototype/$', views.index_prototype, name='index_prototype'),
    url(r'^paternity/$', views.paternity, name='paternity'),
    url(r'^parental/$', views.parental, name='parental'),
    url(r'^offspring/$', views.offspring, name='offspring'),
    url(r'^grandparent/$', views.grandparent, name='grandparent'),
)


traits_web_prototype/models.py
from django import forms
from traits_web_prototype.TraitsEvaluator import TraitsGenotypeMaps
from traits_web_prototype.TraitsEvaluator.TraitsEvaluator import TraitsEvaluator


class TraitsForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super(TraitsForm, self).__init__(*args, **kwargs)

        for name in TraitsEvaluator.get_trait_names():
            choices = [(p,p) for p in TraitsEvaluator.get_trait_phenotypes(name)]
            choices.append(('unknown', 'unknown'))
            self.fields[name] = forms.ChoiceField(choices=choices)


    def get_traits_map(self):
        res = {}
        for name in TraitsEvaluator.get_trait_names():
            res[name] = [self.cleaned_data[name]]
        return res

traits_web_prototype/views.py
from django.http import HttpResponse
from django.shortcuts import render
from traits_web_prototype.TraitsEvaluator.PaternityTester import PaternityTester
from traits_web_prototype.TraitsEvaluator.TraitsEvaluator import TraitsEvaluator
from traits_web_prototype.models import TraitsForm


def index(request):
    return render(request, 'traits_web_prototype/index.html')


def test(request):
    return None


def materials(request):
    return None


def contacts(request):
    return None


def login(request):
    return None


def signup(request):
    return None


def how_it_works(request):
    return None


def index_prototype(request):
    return render(request, 'traits_web_prototype/index_prototype.html')


def paternity(request):
    if request.method == 'POST':
        parent_form1 = TraitsForm(request.POST, prefix='parent_form1')
        parent_form2 = TraitsForm(request.POST, prefix='parent_form2')
        child_form = TraitsForm(request.POST, prefix='child_form')
        if parent_form1.is_valid() and parent_form2.is_valid() and child_form.is_valid():
            tester = PaternityTester(parent_form1.get_traits_map(), parent_form2.get_traits_map(), child_form.get_traits_map())

            no_proof = tester.get_no_proof_traits()
            possible = tester.get_possible_traits()
            is_father = tester.is_parent()


            #TODO: redirect somewhere
            return render(request, 'traits_web_prototype/paternity.html',
                          {
                              'parent_form1': parent_form1,
                              'parent_form2': parent_form2,
                              'child_form': child_form,
                              'no_proof' : no_proof,
                              'possible' : possible,
                              'is_father' : is_father,
                          })

    else:
            parent_form1 = TraitsForm(prefix='parent_form1')
            parent_form2 = TraitsForm(prefix='parent_form2')
            child_form = TraitsForm(prefix='child_form')


    return render(request, 'traits_web_prototype/paternity.html',
              {
                  'parent_form1': parent_form1,
                  'parent_form2': parent_form2,
                  'child_form': child_form,
              })


def parental(request):
    if request.method == 'POST':
        parent_form1 = TraitsForm(request.POST, prefix='parent_form1')
        child_form = TraitsForm(request.POST, prefix='child_form')
        if parent_form1.is_valid()  and child_form.is_valid():
            tester = PaternityTester(parent_form1.get_traits_map(), None, child_form.get_traits_map())

            no_proof = tester.get_no_proof_traits()
            possible = tester.get_possible_traits()
            is_parent = tester.is_parent()


            #TODO: redirect somewhere
            return render(request, 'traits_web_prototype/parental.html',
                          {
                              'parent_form1': parent_form1,
                              'child_form': child_form,
                              'no_proof' : no_proof,
                              'possible' : possible,
                              'is_parent' : is_parent,
                          })

    else:
            parent_form1 = TraitsForm(prefix='parent_form1')
            child_form = TraitsForm(prefix='child_form')


    return render(request, 'traits_web_prototype/parental.html',
              {
                  'parent_form1': parent_form1,
                  'child_form': child_form,
              })


def grandparent(request):
    if request.method == 'POST':
        parent_form1 = TraitsForm(request.POST, prefix='parent_form1')
        child_form = TraitsForm(request.POST, prefix='child_form')
        if parent_form1.is_valid()  and child_form.is_valid():
            grandparent_map = parent_form1.get_traits_map()
            father_map = {}
            for trait in grandparent_map.keys():
                father_map[trait] = TraitsEvaluator.reduce_traits(trait, grandparent_map[trait], [], [])
            print father_map
            tester = PaternityTester(father_map, None, child_form.get_traits_map())

            no_proof = tester.get_no_proof_traits()
            possible = tester.get_possible_traits()
            is_parent = tester.is_parent()


            #TODO: redirect somewhere
            return render(request, 'traits_web_prototype/grandparent.html',
                          {
                              'parent_form1': parent_form1,
                              'child_form': child_form,
                              'no_proof' : no_proof,
                              'possible' : possible,
                              'is_parent' : is_parent,
                          })

    else:
            parent_form1 = TraitsForm(prefix='parent_form1')
            child_form = TraitsForm(prefix='child_form')


    return render(request, 'traits_web_prototype/grandparent.html',
              {
                  'parent_form1': parent_form1,
                  'child_form': child_form,
              })



def offspring(request):
    if request.method == 'POST':
        parent_form1 = TraitsForm(request.POST, prefix='parent_form1')
        parent_form2 = TraitsForm(request.POST, prefix='parent_form2')
        if parent_form1.is_valid() and parent_form2.is_valid():
            #calculate
            result = {}
            teval = TraitsEvaluator()
            for phenotype_name in TraitsEvaluator.get_trait_names():
                result[phenotype_name] = teval.offspring_probs(phenotype_name, [parent_form1.cleaned_data[phenotype_name]], [parent_form2.cleaned_data[phenotype_name]])

            print result

            #TODO: redirect somewhere
            return render(request, 'traits_web_prototype/offspring.html',
                          {
                              'parent_form1': parent_form1,
                              'parent_form2': parent_form2,
                              'result' : result,
                          })

    else:
            parent_form1 = TraitsForm(prefix='parent_form1')
            parent_form2 = TraitsForm(prefix='parent_form2')


    return render(request, 'traits_web_prototype/offspring.html',
              {
                  'parent_form1': parent_form1,
                  'parent_form2': parent_form2,
              })

traits_web_prototype/templates/traits_web_prototype/base.html
{% load staticfiles %}
<html>
  <head>

    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Traits is a free online paternity testing tool. Basic genetic principles, population data from family studies work for you to estimate your paternity chances.">
    <title>Traits – Free online paternity test</title>


    <link href="{% static 'traits_web_prototype/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link  href="{% static 'traits_web_prototype/bootstrap/css/bootstrap-theme.min.css' %}" rel="stylesheet">
    <link  href="{% static 'traits_web_prototype/css/traits.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <script src="{% static 'traits_web_prototype/bootstrap/js/bootstrap.js' %}" type="text/javascript"></script>

    {% block extrahead %}
    {% endblock %}

    <script type="text/javascript">
    $(function(){
    {% block jquery %}
    {% endblock %}
    });
    </script>

   <style>
            .icon-bar {
                background-color:black !important; /* color lines of button in mobile mode */
            }

   </style>

  </head>

  <body>
  <div class="navbar transparent navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand navbar-left" href="{% url 'traits_web_prototype:index' %}">Traits</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-left">
                <li><a href="{% url 'traits_web_prototype:signup' %}">Sign up</a></li>
                <li><a href="{% url 'traits_web_prototype:test' %}">Example</a></li>
                <li><a href="{% url 'traits_web_prototype:how_it_works' %}">How it works</a></li>
                <li><a href="{% url 'traits_web_prototype:materials' %}">Materials</a></li>
                <li><a href="{% url 'traits_web_prototype:contacts' %}">Contacts</a></li>

          </ul>
          <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'traits_web_prototype:login' %}">Log in</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>


    {% block content %}
    {% endblock %}


       <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'traits_web_prototype/bootstrap/js/bootstrap.min.js'%}"></script>
    <script src="{% static 'traits_web_prototype/bootstrap/js/docs.min.js'%}"></script>
  </body>
</html>

traits_web_prototype/templates/traits_web_prototype/base_prototype.html
{% load staticfiles %}
<html>
  <head>

      <meta charset="utf-8" />
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>Traits</title>


    <link href="{% static 'traits_web_prototype/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link  href="{% static 'traits_web_prototype/bootstrap/css/bootstrap-theme.min.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

        <style>
            body {
                padding-top: 50px; /* 60px to make the container go all the way to the bottom of the topbar */
            }
        </style>

        <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <script src="{% static 'traits_web_prototype/bootstrap/js/bootstrap.js' %}" type="text/javascript"></script>
        {% block extrahead %}
        {% endblock %}
        <script type="text/javascript">
        $(function(){
        {% block jquery %}
        {% endblock %}
        });
        </script>
  </head>

  <body>
  <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'traits_web_prototype:index_prototype' %}">Traits</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
                <li><a href="{% url 'traits_web_prototype:paternity' %}">Paternity</a></li>
                <li><a href="{% url 'traits_web_prototype:parental' %}">Parental</a></li>
                <li><a href="{% url 'traits_web_prototype:offspring' %}">Offspring</a></li>
              <li><a href="{% url 'traits_web_prototype:grandparent' %}">Grandparent</a></li>
                <li><a href="{% url 'admin:index' %}">Admin</a></li>


          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>


    {% block content %}
    {% endblock %}


       <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'traits_web_prototype/bootstrap/js/bootstrap.min.js'%}"></script>
    <script src="{% static 'traits_web_prototype/bootstrap/js/docs.min.js'%}"></script>
  </body>
</html>

traits_web_prototype/templates/traits_web_prototype/grandparent.html
{% extends "traits_web_prototype/base_prototype.html" %}
{% load bootstrap %}

{% block content %}
<div class="container-fluid">
        <h1 class="page-header">Grandparent test</h1>

            <form action="{% url 'traits_web_prototype:grandparent' %}" method="post">{% csrf_token %}

            <div class="row-fluid">
                <div class="col-lg-4">
                    <h2>Potential Grandparent</h2>
                    {{ parent_form1 | bootstrap }}
                </div>
                <div class="col-lg-4">
                    <h2>Child</h2>
                    {{ child_form | bootstrap}}
                </div>
            </div>

            <div class="row-fluid">
                <div class="col-lg-8">
                    <button type="submit" class="btn btn-primary btn-lg" >Calculate</button>
                </div>
            </div>

            </form>

            <div class="row-fluid">
                <div class="col-lg-8">
                    <h2>Result</h2>
                    {% if is_parent %}
                        <b>Unknown</b>
                    {% else %}
                        <b>Probably, not grandparent</b>
                    {% endif %}
                    <br>
                    {% if possible %}
                        <p>Possible traits</p>
                          <table id="formset" class="table">
                        {% for trait, trait_dict in possible.items %}
                          <tr>
                          <td>
                              {{ trait }}
                          </td>
                          <td>
                              {{ trait_dict }}
                          </td>
                          </tr>
                        {% endfor %}
                        </table>
                    {% endif %}
            <br>
                    {% if no_proof %}
                        <p>Not matching traits</p>
                          <table id="formset" class="table">
                        {% for trait, trait_dict in no_proof.items %}
                          <tr>
                          <td>
                              {{ trait }}
                          </td>
                          <td>
                              {{ trait_dict }}
                          </td>
                          </tr>
                        {% endfor %}
                        </table>
                    {% endif %}
                </div>
            </div>
</div>

{% endblock %}

traits_web_prototype/templates/traits_web_prototype/index.html
{% extends "traits_web_prototype/base.html" %}
{% load staticfiles %}

{% block content %}

    <div class="container-fluid main-head full">
             <h1 >Paternity test online</h1>
             <hr class="light">
             <p class="lead">Model your paternity test online. Here and now<br>
                                          Known your chances before going to a lab<br>
                                          Use basic genetics to get peace of mind</p>
        <a href="#" class="btn btn-lg btn-outline-inverse">Get tested</a>


    </div>

    <div class="container-fluid marketing">
        <h2>Let your DNA answer paternity questions now</h2>
        <p class="lead">Traits brings biological knowledge of paternity online in a way that everyone can understand. It is for you if you are in doubt or just want to try a new technology</p>
    </div>
    <hr class="half-rule">
    <div class="container-fluid features">
        <div class="row-fluid">
          <div class="col-sm-3">
            <img src="assets/img/sass-less.png" alt="Simple" class="img-circle" style="width: 140px; height: 140px;">
            <h3>Simple</h3>
            <p>You already have information to estimate your paternity results in 10 minutes. <br><a href="{% url 'traits_web_prototype:test' %}">Give it a try</a></p>
          </div>
          <div class="col-sm-3">
            <img src="assets/img/devices.png" alt="Technological" class="img-circle" style="width: 140px; height: 140px;">
            <h3>Technology</h3>
            <p>Our algorithms use basic genetic principals, population data and recent scientific reports to model your paternity test. We constantly update our estimations as new scientific data appears.<br><a href="{% url 'traits_web_prototype:how_it_works' %}">Learn more</a></p>
          </div>
          <div class="col-sm-3">
            <img src="assets/img/components.png" alt="Free" class="img-circle" style="width: 140px; height: 140px;">
            <h3>Free</h3>
            <p>Online paternity test is free of charge.</p>
          </div>
          <div class="col-sm-3">
            <img src="assets/img/components.png" alt="Safe" class="img-circle" style="width: 140px; height: 140px;">
            <h3>Safe</h3>
            <p>Your privacy is guarantied by multiple levels of security protocols and encryption.</p>
          </div>
        </div>
  </div>
<hr class="half-rule">
    <div class="container-fluid subscribe">

    <div class="col-sm-4 col-sm-offset-5">


    <div class="input-group">
        <span class="input-group-addon" id="basic-addon1">@</span>
        <input type="email" class="form-control" placeholder="Email">
      <span class="input-group-btn">
        <button class="btn btn-primary" type="button">Subscribe</button>
      </span>

    </div><!-- /input-group -->
        <p class="text-muted">To receive genetic and paternity testing updates.</p>
    </div>

    </div>
<hr class="half-rule">
    <div class="container-fluid">
    <div class="col-sm-6 info">
        <h2>Paternity calculation</h2>

        <p>How likely that a brown-eyed child has blue-eyed parents? <i>Unlikely.</i><br><br>
        Can a child with the B blood type have parents with the A blood type? <i>Impossible in 99.9% cases.</i><br><br>

        Genes are passed from parents to children under well-known laws. There are traits with relatively simple genetic basis like eye color, form of ear or hair color. Our algorithms make use of these genetic laws and population data from family studies. We can estimate if a combination of traits of a child and parents is possible.<br><br>


        Find out how likely a combination of the traits in your case.</p>
        <a href="#" class="btn btn-lg btn-primary">Get tested</a>

    </div>
    <div class="col-sm-6 info-img">
    <img src="{% static 'traits_web_prototype/images/lab.jpg' %}" alt="Laboratory test">
    </div>
    </div>
<hr class="half-rule">

    <div class="container-fluid text-center steps  ">
    <div class="col-sm-4">
    <h3>1. Insert visible traits</h3>
    </div>
    <div class="col-sm-4">
    <h3>2. Get the report immediately</h3>
    </div>
    <div class="col-sm-4">
    <h3>3. Stay updated</h3>
    </div>
    </div>
<hr class="half-rule">

    <div class="container-fluid reviews">
     <div class="row">
            <div class="col-lg-4">
                <img class="img-circle" src="{% static 'gmql/images/p1.jpg' %}" alt="Generic placeholder image" style="width: 140px; height: 140px;">

                <h4>Randy</h4>

                <p>"Thank you!
There was a guy who said that he’s my son. Your site showed that it is not true, so I realized that he’s a cheater."</p>
            </div>
            <!-- /.col-lg-4 -->
            <div class="col-lg-4">
                <img class="img-circle" src="{% static 'gmql/images/p2.jpg' %}" alt="Generic placeholder image" style="width: 140px; height: 140px;">

                <h4>Emily</h4>

                <p>"We used your paternity test online to find my father. We had two candidates. I just did two online tests and one of them gave my positive result."</p>
            </div>
            <!-- /.col-lg-4 -->
            <div class="col-lg-4">
                <img class="img-circle" src="{% static 'gmql/images/p3.jpg' %}" alt="Generic placeholder image" style="width: 140px; height: 140px;">

                <h4>Lilly</h4>

                <p>"I just checked that my children are really my children. Thank you for the nice resource!"</p>
            </div>
            <!-- /.col-lg-4 -->
        </div>
        <!-- /.row -->
    </div>


        <!-- FOOTER -->
        <footer>
            <h3 class="text-center">About</h3>
            <hr>
            <p class="pull-right"><a href="{% url 'traits_web_prototype:index' %}">Back to top</a></p>

            <p>&copy; {% now "Y" %} Paternity test online. &middot; <a href="{% url 'traits_web_prototype:index' %}">Privacy</a> &middot; <a
                    href="{% url 'traits_web_prototype:index' %}">Terms</a></p>
        </footer>



{% endblock %}

traits_web_prototype/templates/traits_web_prototype/index_prototype.html
{% extends "traits_web_prototype/base_prototype.html" %}
{% load staticfiles %}

{% block content %}

    <div class="container-fluid">

    <h1 class="page-header">Tests</h1>
         <div class="row-fluid">
            <div class="col-lg-2">
                <a href="{% url 'traits_web_prototype:paternity' %}">
                    <img class="img-circle" src="{% static 'traits_web_prototype/images/paternity.jpg' %}" alt="Generic placeholder image" style="width: 140px; height: 140px;">
                    <h4>Paternity testing</h4>
                </a>
            </div>
             <div class="col-lg-2">
                <a href="{% url 'traits_web_prototype:parental' %}">
                    <img class="img-circle" src="{% static 'traits_web_prototype/images/parental.jpg' %}" alt="Generic placeholder image" style="width: 140px; height: 140px;">
                    <h4>Parental testing</h4>
                </a>
            </div>
            <div class="col-lg-2">
                <a href="{% url 'traits_web_prototype:offspring' %}">
                    <img class="img-circle" src="{% static 'traits_web_prototype/images/offspring.jpg' %}" alt="Generic placeholder image" style="width: 140px; height: 140px;">
                    <h4>Offspring testing</h4>
                </a>
            </div>
             <div class="col-lg-2">
                <a href="{% url 'traits_web_prototype:grandparent' %}">
                    <img class="img-circle" src="{% static 'traits_web_prototype/images/grandparent.jpg' %}" alt="Generic placeholder image" style="width: 140px; height: 140px;">
                    <h4>Grandparent testing</h4>
                </a>
            </div>
          </div><!-- /.row -->
                </div>

{% endblock %}


traits_web_prototype/templates/traits_web_prototype/offspring.html
{% extends "traits_web_prototype/base_prototype.html" %}

{% load bootstrap %}

{% block content %}
    <div class="container-fluid">
        <h1 class="page-header">Offspring test</h1>

        <form action="{% url 'traits_web_prototype:offspring' %}" method="post">{% csrf_token %}

        <div class="row-fluid">
            <div class="col-lg-4">
                <h2>Parent 1</h2>
                {{ parent_form1 | bootstrap }}
            </div>

            <div class="col-lg-4">
                <h2>Parent 2</h2>
                {{ parent_form2 | bootstrap }}
            </div>
        </div>

        <div class="row-fluid">
            <div class="col-lg-8">
                <button type="submit" class="btn btn-primary btn-lg" >Calculate</button>
            </div>
        </div>

        </form>

    <div class="row-fluid">
            <div class="col-lg-8">
                {% if result %}
                    <h2>Child</h2>
                      <table id="formset" class="table">
                        {% for trait, trait_dict in result.items %}
                          <tr>
                          <td>
                              {{ trait }}
                          </td>
                          <td>
                              {{ trait_dict }}
                          </td>
                          </tr>
                        {% endfor %}
                        </table>
                {% endif %}
            </div>
    </div>
    </div>

{% endblock %}

traits_web_prototype/templates/traits_web_prototype/parental.html
{% extends "traits_web_prototype/base_prototype.html" %}
{% load bootstrap %}

{% block content %}
<div class="container-fluid">
        <h1 class="page-header">Paternity test</h1>

            <form action="{% url 'traits_web_prototype:parental' %}" method="post">{% csrf_token %}

            <div class="row-fluid">
                <div class="col-lg-4">
                    <h2>Potential Parent</h2>
                    {{ parent_form1 | bootstrap }}
                </div>
                <div class="col-lg-4">
                    <h2>Child</h2>
                    {{ child_form | bootstrap}}
                </div>
            </div>

            <div class="row-fluid">
                <div class="col-lg-8">
                    <button type="submit" class="btn btn-primary btn-lg" >Calculate</button>
                </div>
            </div>

            </form>

            <div class="row-fluid">
                <div class="col-lg-8">
                    <h2>Result</h2>
                    {% if is_parent %}
                        <b>Unknown</b>
                    {% else %}
                        <b>Probably, not parent</b>
                    {% endif %}
                    <br>
                    {% if possible %}
                        <p>Possible traits</p>
                          <table id="formset" class="table">
                        {% for trait, trait_dict in possible.items %}
                          <tr>
                          <td>
                              {{ trait }}
                          </td>
                          <td>
                              {{ trait_dict }}
                          </td>
                          </tr>
                        {% endfor %}
                        </table>
                    {% endif %}
            <br>
                    {% if no_proof %}
                        <p>Not matching traits</p>
                          <table id="formset" class="table">
                        {% for trait, trait_dict in no_proof.items %}
                          <tr>
                          <td>
                              {{ trait }}
                          </td>
                          <td>
                              {{ trait_dict }}
                          </td>
                          </tr>
                        {% endfor %}
                        </table>
                    {% endif %}
                </div>
            </div>
</div>

{% endblock %}